version: '3.7'
volumes:
  texterify-database:
    external:
      name: texterify-database
  texterify-assets:
    external:
      name: texterify-assets
services:
  db:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:12.2
    volumes:
      - texterify-database:/var/lib/postgresql/data
  app:
    image: chrztoph/texterify:${TEXTERIFY_TAG}
    env_file:
      - secrets.env
    depends_on:
      - db
    volumes:
      - texterify-assets:/var/www/texterify/storage
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
