version: '3.7'
volumes:
  texterify-database:
    external:
      name: texterify-database
services:
  db:
    image: postgres
    volumes:
      - texterify-database:/var/lib/postgresql/data
  app:
    image: chrztoph/texterify:${TEXTERIFY_TAG}
    environment:
      - SECRET_KEY_BASE=${TEXTERIFY_SECRET_KEY}
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
