version: '3.7'
volumes:
  texterify-database:
    external:
      name: texterify-database
  texterify-assets:
    external:
      name: texterify-assets
services:
  db:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:12.2
    volumes:
      - texterify-database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    image: chrztoph/texterify:${TEXTERIFY_TAG}
    env_file:
      - secrets.env
      - .env
    depends_on:
      - db
    volumes:
      - texterify-assets:/var/www/texterify/storage
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        BUILDER_IMAGE: chrztoph/texterify:${TEXTERIFY_TAG}
    depends_on:
      - app
    ports:
      - 80:80
  sidekiq:
    image: chrztoph/texterify:${TEXTERIFY_TAG}
    env_file:
      - secrets.env
      - .env
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq
    volumes:
      - texterify-assets:/var/www/texterify/storage
  redis:
    image: redis:6.2.0-alpine
